### ISSUE TITLE
Gemfile option not working

### ISSUE THREAD

**Issue by niels-s** [wercker/step-bundle-install#10]
I'm trying to use this step to install my gems and configure a specific Gemfile but the step isn't using the option. See my step output below:

![screen shot 2016-02-22 at 11 10 39](https://cloud.githubusercontent.com/assets/1531951/13215356/f4d1cc2a-d954-11e5-857f-c1cb4f791bb5.png)

And this is the snippet how I configure my .wercker.yml file:

```
    - bundle-install:
        gemfile: /go/src/github.com/blendle/brains/features/Gemfile
```

I've looked into the step script and it's expecting the `WERCKER_BUNDLE_INSTALL_GEMFILE` env var to exported, which is exported if you have a look at the step output but never used by the step itself.
Could you tell me if I'm doing something wrong here? Or is something not working properly?

**Comment by hatchan** [comment]
The path gets prefixed with `$PWD`, which in your case if empty. The check does add a trailing slash to the $PWD (https://github.com/wercker/step-bundle-install/blob/master/run.sh#L81)

If you use a relative path, then it should work.

**Comment by niels-s** [comment]
I've tried this already then I got the following: 
![screen shot 2016-02-22 at 14 56 10](https://cloud.githubusercontent.com/assets/1531951/13220105/7b3b2e9a-d974-11e5-85ba-a37500e8cfb6.png)
