### ISSUE TITLE
2.0.1 breaks bundle-install step

### ISSUE THREAD

**Issue by jhendley25** [wercker/step-bundle-install#14]
cd $WERCKER_SOURCE_DIR
$ export WERCKER_STEP_ROOT="/wercker/steps/wercker/bundle-install/2.0.1"
$ export WERCKER_STEP_ID="7b3f5b07-1c73-4b55-a83d-756160f69745"
$ export WERCKER_STEP_NAME="bundle-install"
$ export WERCKER_REPORT_NUMBERS_FILE="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/numbers.ini"
$ export WERCKER_REPORT_MESSAGE_FILE="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/message.txt"
$ export WERCKER_REPORT_ARTIFACTS_DIR="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/artifacts"
$ mkdir -p $WERCKER_REPORT_ARTIFACTS_DIR
$ export WERCKER_STEP_TEMP="/tmp/$WERCKER_STEP_ID"
$ source '/wercker/wercker-build-essentials/init.sh'
$ mkdir -p $WERCKER_STEP_TEMP
$ export WERCKER_BUNDLE_INSTALL_CLEAR_PATH="true"
$ source "$WERCKER_STEP_ROOT/run.sh"
Gemfile found. Start bundle install.
bundler gem is available, and will not be installed by this step
type bundle: bundle is /usr/local/bin/bundle
bundle version: Bundler version 1.3.0
bundle install --path /cache/bundle-install/ --retry 3
Unknown switches '--retry'

**Comment by jhendley25** [comment]
FYI it works when setting bundle-install@2.0.0 in wercker.yml

**Comment by hatchan** [comment]
Using `2.0.0` probably also fails, there was a bug which didn't catch any failed commands (see logs). I recommend using a box with a newer Ruby version, such as the [box-rvm](https://github.com/wercker/box-rvm). You could also update the bundler gem as part of your build script. Otherwise you can lock the version to `bundle-install@1.1.3`.

**Comment by captn3m0** [comment]
The wercker documentation still refers to ruby as the box to use: https://docs.oracle.com/en/cloud/iaas/wercker-cloud/wercm/quickstarts/languages/quickstarts-ruby/

The rvm box is marked as deprecated. Is there a way to use bundler 2.x?
