### ISSUE TITLE
Control which version of bundler is installed

### ISSUE THREAD

**Issue by rzane** [wercker/step-bundle-install#5]
Some projects require specific bundler versions that offer newer features. For example, source blocks are only available in 1.7+.

**Comment by hatchan** [comment]
This doesn't sound to complicated. Will take a look at it later this week

For now you can work around this by installing it manually using a script step: `sudo gem install bundler --no-rdoc --no-ri --version '>=1.7'`

**Comment by rzane** [comment]
Awesome thanks!

**Comment by hatchan** [comment]
Released the new version, checkout the readme for the `version` option

**Comment by rzane** [comment]
Awesome. Thanks!
